[Refactor] QueryDsl의 @QueryProjection을 이용하여 N+1문제 해결
idorm/idorm-server pull request #69
Opened 2024-04-14 14:55 UTC by songhyeon99

❗️ 이슈 번호
close #63

📝 구현 내용
N+1 문제를 해결하기 위해 배치 사이즈를 조정하고, 데이터 조회용 DTO를 별도로 생성하여 이를 클라이언트에 반환할 때 사용하는 DTO로 재조립하는 방법을 사용했습니다.

🙇🏻‍♂️ 리뷰어에게 부탁합니다!

💡 참고 자료

2024-04-15 11:04 UTC, nahyeon99 requested changes
리뷰 이번에는 꼼꼼히 확인해주세요....🥺ㅠㅠ 중복 리뷰는 안 남겼는데 같은 케이스는 다 적용해주시면 됩니다.

2024-04-15 11:04 UTC, nahyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/LoadPostAdapter.java
> +        return postRepository.findById(postId).orElseThrow(() -> new NotFoundPostException());
orElseThrow() 던지는 코드에 대한 개행이 현재 제각기 다릅니다.  아래 코드와 같이 개행 통일 해주세요!

```java
    public Post findById(Long postId) {
        return postRepository.findById(postId)
            .orElseThrow(() -> new NotFoundPostException());
    }
```

2024-04-15 11:04 UTC, nahyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/LoadPostAdapter.java
> +    private final PostRepository postRepository;
현재 커뮤니티, 캘린더 패키지 내 탭 사이즈 포맷팅이 전체적으로 2로 설정되어있는 파일이 많습니다. 4로 설정 변경 후 담당 패키지 전체적으로 리 포맷팅 해주세요!

2024-04-15 11:04 UTC, nahyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/LoadPostAdapter.java
> +    public Post findByPostIdWithLock(Long postId) {
해당 메서드를 호출하게 되는 상위 계층에서는 Lock을 거는 지 여부를 알 필요가 없다고 생각합니다. 추상화로 캡슐화해뒀는데, 굳이 상위 계층에서 호출할 때 하위 계층의 불필요한(구체적인) 정보를 생각하게 만드는 과정은 제거해도 되지않을까요? 

레포짓 레이어는 괜찮을 것 같은데, 포트 및 어댑터에서 호출되는 메서드의 네이밍은 **findByPostId** 로 수정하는 게 어떨까요? (여기서 호출자는 서비스가 되겠네요!)

2024-04-15 11:04 UTC, nahyeon99 commented on src/main/java/idorm/idormServer/community/post/application/port/in/dto/PostListData.java
> +    }
레코드 타입은 아래처럼 생성자를 만들 수 있습니다. 현재 생성자와 같은 역할을 한다고 보시면 됩니다!

```java
	@QueryProjection
	public PostListData {
	}
```

2024-04-15 11:04 UTC, nahyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/LoadPostAdapter.java
> +    public Page<PostListData> findPostsByDormCategoryAndIsDeletedFalse(DormCategory dormCategory, Pageable pageable) {
현재 dto 클래스명의 네이밍은 *Request, *Response 로 통일되어 있습니다. 또한 PostListData에 대한 네이밍 자체도 크게 묶는 부모 dto인지 자식 dto인지 헷갈립니다. 

PostSummaryResponse 나 PostOneSummaryResponse 와 같이 조금 더 길더라도 명확하게 수정해주세요! 대신 규격 통일은 required 입니다.

2024-04-15 11:04 UTC, nahyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/LoadPostAdapter.java
> +        return responses.isEmpty() ? new ArrayList<>() : responses;
어댑터에서 위와 같이 반환해주고 있는 코드를 다음 코드로 전부 수정하는 것이 좋을 것 같습니다. 

jpa는 보통 리스트 반환 시 데이터가 없으면 emptyList를 반환하지만, 간혹가다가 null을 반환하는 경우가 있다고 합니다. 
따라서 emptyList 혹은 리스트 반환 시 그대로 반환해주고, null 리턴 시 이에 대한 대응을 위해서 아래와 같이 수정 부탁드립니다!

`
return responses != null ? responses : Collections.emptyList();
`

2024-04-15 11:04 UTC, nahyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/PostCustomRepositoryImpl.java
> +            .where(dormitoryPostCond(dormCategory))
eq에 대한 역할만 가지는 메서드라면 dormCategoryEq 네이밍이 좋을 것 같습니다. 
여러 조건이 combine이 된 어떠한 로직에 대한 조건이라면 그 로직을 명확하게 드러낼 수 있는 네이밍이 좋을 것 같구요. 해당 예시로는 "인기 게시글 조건" 으로 topPostCond 를 들 수 있습니다.

2024-04-15 11:04 UTC, nahyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/PostCustomRepositoryImpl.java
> +    }
생성자 네이밍을 변경될 클래스명 + From 으로 변경하는 것이 더 명확할 것 같습니다. PostSummaryOneResponse로 변경된다면, PostSummaryOneResponseFrom이요!

2024-04-15 11:04 UTC, nahyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/PostCustomRepositoryImpl.java
> +    }
옼 처음보는 문법이네요~ 👍👍

-999는 매직 리터럴이기 때문에 상수 처리하는 것이 좋을 것 같습니다. 해당 클래스보다는, Post 엔티티 클래스에서 전역 접근이 가능한 DELETED_MEMBER_ID 와 같은 상수를 만들어서 사용하는 게 어떨까요? _(레퍼런스: https://javabom.tistory.com/28)_

메서드 네이밍은 convertNickname은 어떨까요? 조금 애매한데 더 명확한 네이밍 있다면 그걸로.. 해주세요!

2024-04-18 06:16 UTC, songhyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/PostCustomRepositoryImpl.java
> +            .where(dormitoryPostCond(dormCategory))
해당 부분은 기숙사 게시글 목록을 조회하는 부분으로, dorm과 isDeleted로 필터링 하는 부분입니다. 따라서 두 조건이 조합되어 있어 cond으로 명명했습니다.

2024-04-18 06:16 UTC, songhyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/LoadPostAdapter.java
> +    public Page<PostListData> findPostsByDormCategoryAndIsDeletedFalse(DormCategory dormCategory, Pageable pageable) {
request와 response는 클라이언트와 서버에서 주고 받는 dto에 해당되는 반면, 위의 dto는 데이터베이스에서 데이터를 조회하여 매핑하는 dto로 사용했기 때문에 request와 response가 아닌 data로 사용했습니다.
또한 summary가 아닌 list를 사용한 이유는 게시글의 데이터가 리스트로 담겨 있다는 것을 강조하기 위함입니다.

2024-04-18 06:16 UTC, songhyeon99 commented on src/main/java/idorm/idormServer/community/post/application/port/in/dto/PostListData.java
> +    }
@QueryProjection는 DTO로 반환하기 위해 직접 매핑하는 것으로 알고 있습니다. 따라서, 모든 필드에 대한 생성자를 명시적으로 작성해야하는 것으로 알고 있습니다.

2024-04-18 06:20 UTC, songhyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/LoadPostAdapter.java
> +    public Post findByPostIdWithLock(Long postId) {
맞는 말인것 같습니다. 호출하는 쪽에서 Lock 작동 방식은 몰라도 되는 것 같습니다. 반영하겠습니다!

2024-04-21 16:09 UTC, songhyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/PostCustomRepositoryImpl.java
> +    }
좋은것 같습니다!

2024-04-21 16:10 UTC, songhyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/PostCustomRepositoryImpl.java
> +    }
상수로 표현하는 것이 어떤 역할을 하는지 정확하고 쉽게 이해할 수 있어 좋은 것 같네요! 수정할게요!

2024-05-04 10:17 UTC, nahyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/LoadPostAdapter.java
> +    public Post findByPostIdWithLock(Long postId) {
현재 DB에 Lock을 걸어서 게시글을 조회하는 경우는 게시글 공감이 업데이트될 때 뿐입니다. 따라서 findByPostIdWithLock 보단 **findByIdForLikeUpdate** 혹은 **findByIdForPostLike** 중에 택하는 것이 좋을 것 같아요.

2024-05-04 11:19 UTC, nahyeon99 commented on src/main/java/idorm/idormServer/community/post/adapter/out/persistence/LoadPostAdapter.java
> +    public Page<PostListData> findPostsByDormCategoryAndIsDeletedFalse(DormCategory dormCategory, Pageable pageable) {
회의를 통해 다음과 같이 적용되었습니다.

1. 기존의 PostListData는 querydsl 조회 목적의 DTO이기 때문에, 기존의 dto 패키지 내에 querydsl 패키지를 만들어서 위치시킨다.
2. 네이밍은 PostListResponse -> PostOneSummaryResponse로, PostListData -> PostSearchResponse로 변경한다.

2024-05-04 11:27 UTC, merged